
spring:
  datasource:
    url: jdbc:mysql://47.104.158.128:3306/secondModul?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
        show-sql: true
      database: mysql
      open-in-view: true


server:
  port: 8088

